project:
  type: website

website:
  title: "Customer Segmentation"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

publish:
  quarto-pub:
    type: quarto-pub
    site: test_blog


